[package]
name = "example:hello-cli"
version = "0.1.0"

[framework]
host = "../../cli/components/host/host.component.wasm"
core = "../../cli/components/core/core.component.wasm"
registry = "registry/registry.component.wasm"

[[command]]
name = "greet"
package = "example:greeter"
plugin = "plugins/greeter/greeter.component.wasm"

[output]
path = "dist/hello-cli.component.wasm"
