[package]
name = "wacli-host"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[lib]
name = "wacli_host"
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = { workspace = true }
